export const protectedRoutes = [
  "/",
  "/post",
  "/user",
  "/user/:page*",
  "/profile",
  "/checkout",
  "/profile/:page*",
  "/user/dashboard",
  "/admin/dashboard",
  "/admin",
  "/admin/:page*",
  "/login",
  "/signup",
];
